### ISSUE TITLE
when sending failed. should configure the interval instead of trying to send again.

### ISSUE THREAD

**Issue by FallenCrystal** [SkyWatcher2019/LimboQueue#3]
![image](https://user-images.githubusercontent.com/71176602/220365362-6fcde5f8-dd9f-4153-9c8a-b95c4007b707.png)
although i am using via. i know that there may be no other way to really know if a server is full online. but at least dont repeat attempts to send instantly :\

**Comment by SkyWatcher2019** [comment]
Wrong plugin (https://github.com/elytrium/limboreconnect)

**Comment by FallenCrystal** [comment]
bruh
