### ISSUE TITLE
Suggestion for improvement. Permission to bypass queue.

### ISSUE THREAD

**Issue by mmaniaque** [SkyWatcher2019/LimboQueue#5]
Hello,

Having VIP players, I would like to allow them to bypass the queue when the server is full, I use a plugin on Spigot that allows access to a full server but LimboQueue prevents this from working, so it would be nice if the person has permission that it forces him to connect to the server even when it is full.

Best regards

**Comment by SkyWatcher2019** [comment]
![image](https://github.com/Elytrium/LimboQueue/assets/62600934/609b2eaa-f419-4d91-8c51-1d44c4432a9c)
Can't push update for some reason

**Comment by SkyWatcher2019** [comment]
Done

**Comment by mmaniaque** [comment]
Do I have to compile it myself or will an updated .jar be made?

Thanks a lot for the speed!

**Comment by mmaniaque** [comment]
https://github.com/Elytrium/LimboQueue/actions/runs/5101094962/jobs/9169736608

**Comment by mmaniaque** [comment]
Despite permission in the Administrator role and updating the plugin I'm still stuck in the queue. When I try to connect directly without going through Velocity, I can access the server even if the slots are full.

I use LuckPerms for the permissions set on the Velocity proxy.

Thank you again for your promptness.

![D1jOzGiOoTQYv1w1tiRm4](https://github.com/Elytrium/LimboQueue/assets/12367033/32de824f-7a85-4289-a0e9-a55a0a9f0a3f)

**Comment by SkyWatcher2019** [comment]
Can you try this one? (debug)
[LimboQueue-1.0.1.jar.txt](https://github.com/Elytrium/LimboQueue/files/11584814/LimboQueue-1.0.1.jar.txt)

**Comment by mmaniaque** [comment]
Thank you for your feedback. Your debugging .jar doesn't work. The jar works but does not display a debug.
![fCjZnn5s6HAO5SQ9o8vdL](https://github.com/Elytrium/LimboQueue/assets/12367033/6a0173ed-8534-4c1e-a441-fc8a3425990a)

**Comment by mmaniaque** [comment]
Hello,

I wanted to know if you had any feedback regarding my bypass problem which is not being performed. The .jar you sent does not display any debug line.

Best regards
